#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

basename="${1##*/}"
dirname="${1%/*}"

echo "$dirname"

if [[ "$dirname" != "$1" ]]
then
	cd "$dirname"
fi

# XXX Try to find a working editor in a better way.
for editor in gvim kate gedit
do
	if which "$editor" &> /dev/null
	then
		"$editor" "$basename" &
		break
	fi
done

nice latexmk -r "/etc/latex-edit/latexmkrc" -pvc -pdf "$basename"
