#!/bin/bash
# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

basename="$(basename "$1")"
dirname="$(dirname "$1")"

cd "$dirname"

gvim "$basename" &

latexmk -pvc -pdf "$basename"
